### ISSUE TITLE
ERROR - Incorrect labels in image: [[0 0 0 ... 5 5 5]

### ISSUE THREAD

**Issue by matheuscass** [jerisalan/RCNN-Segmentation#1]
Hey, I'm trying to run the code with the stanford dataset and I'm getting the following error: 
ERROR - Incorrect labels in image: [[0 0 0 ... 5 5 5]
 [0 0 0 ... 5 5 5]
 [0 0 0 ... 5 5 5]
 ...
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]]

**Comment by jerisalan** [comment]
If you are using the Stanford dataset, then you need to set the RGB values for all the class labels in your dataset correctly in the "category_maps/stanford_bground_categories.txt" file. This has been clearly mentioned in the project README!
The code put here has been run with my custom dataset so I have configured the category maps specific to my dataset. 
Check this for reference - https://github.com/NP-coder/CLPS1520Project/blob/master/category_maps/stanford_bground_categories.txt
